name: Frakcje
version: 1.0
main: me.gacekmpl2.Main
api-version: 1.17
depend:
  - PlaceholderAPI
authors: [ GacekMPL2 ]

commands:
  boyfarmer:
    aliases:
      - bf
  yt:
    usage: /yt
    aliases:
      - youtube
      - live
      - link
  easyhc:
    usage: /easyhc`